name: Deploy to Docker Hub

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with javac
        run: |
          mkdir -p out
          javac -d out $(find src -name "*.java")

      - name: Create jar file
        run: |
          jar -cvf prithvi.jar -C out .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            jayadityadocker/prithvi:latest
            jayadityadocker/prithvi:${{ github.sha }}
          platforms: linux/amd64,linux/arm64

      - name: Sanity check: run Docker image
        run: |
          docker pull jayadityadocker/prithvi:${{ github.sha }}
          docker run -d --name prithvi-test jayadityadocker/prithvi:${{ github.sha }}
          sleep 5 # Give the container a moment to start
          docker stop prithvi-test
          docker rm prithvi-test

