name: Deploy to Docker Hub

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  debug_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Print success message
        run: echo "CD WORKFLOW TRIGGERED SUCCESSFULLY!"